manifest.json, overrides/config/enderio/recipes/user/user_recipes.xml, overrides/config/jei/itemBlacklist.cfg, overrides/config/undergroundbiomes.cfg, overrides/scripts/AppliedEnergistics2.zs, overrides/scripts/BloodMagic.zs, overrides/scripts/Botania.zs, overrides/scripts/ContentTweakerBlocks.zs, overrides/scripts/ContentTweakerRecipes.zs, overrides/scripts/DankNull.zs, overrides/scripts/DivineRPGVetheaRecipes.zs, overrides/scripts/EnderUtilities.zs, overrides/scripts/EvilCraft.zs, overrides/scripts/ExtraCells2.zs, overrides/scripts/IndustrialForegoing.zs, overrides/scripts/MoreTweaker.zs
Mod updates, balance changes, bugfixes, quest tweaks, and some QoL included.
<h1>Changes:</h1>
<h2>Mod Updates:</h2>
DJ2Addons: 1.0.1 -> 1.1.0<br>
Thaumic Augmentation: 2.1.5 -> 2.1.7<br>
Roots: 3.1.4 -> 3.1.5<br>
UB: 1.3.11 -> 1.3.14<br>
ModTweaker: 4.0.20.4 -> 4.0.20.11<br>
CraftTweaker: 4.1.20.674 -> 4.1.20.675<br>
UniDict: 3.0.8 -> 3.0.10<br>
JEI: 4.16.1.301 -> 4.16.1.302<br>
LibVulpes: build -84 -> build -25<br>
WanionLib: 2.5 -> 2.9<br>
Hammer Lib: 2.0.6.28 -> 2.0.6.32<br>
<h2>Bugfixes:</h2>
Fix Gas Storage Housing uses being missing.<br>
EnderIO Attractor Crystal recipe is now actually craftable.<br>
Fix Evilcraft's Vengeance Pickaxe crafting with an incorrect enchantment.<br>
Glod Blocks now drop the correct NBT tagged Glod Block.<br>
Fix Roots Bowl duplication glitch.<br> …
=> Maintain june 2022

overrides/config/roots/tools.cfg
I had thought this was done and fixed months ago. Ah well.
=> Disable roots tools on custom dungeon blocks

overrides/config/jei/itemBlacklist.cfg
a whole bunch of new blocks were generated by underground biomes, and those blocks had facade versions that should have been hidden. so, this hides them.
=> hide the facades created by #760 from jei

overrides/scripts/LightningCraft.zs
this makes the lightningcraft crusher is no longer needed. it prevents obtaining the bonemeal via the crusher, instead making it require a recipe in the Lightningcraft Infusion Multiblock.
=> Make Guards Bonemeal use the LIM instead of Crusher

overrides/scripts/AbyssalCraft.zs
summoning anticows was moved to roots in #891, removing this was just forgotten.
=> remove anticow abyssalcraft summoning

overrides/config/enderio/recipes/user/user_recipes.xml
prevents a boss fight component from being captureable in an EnderIO Soul Vial.
=> prevent thaumic augmentation boss shield from being captured via soul vial

overrides/scripts/Chisel.zs
because they crash when trying to be chiseled in-world.
fix #932
=> Remove Bibliocraft Lamp and Lantern Chisel groups

overrides/scripts/AbyssalCraft.zs
Allow ownership gaining via hidden shapeless crafting. Technically it only removes ownership, but crafting automatically sets ownership to the player crafting.
This is needed for the same reason as Blood Magic in #917 and because its tied to the username, which can change.
=> Necronomicon variants ownership clearing

overrides/config/bloodmagic/bloodmagic.cfg
prevents bug codename "ouroboros", wherein the snake returns to life and full health instead of dying.
death to eternity.
victory ever transient.
=> prevent bewitchment snakes from Blood Magic's WoS

overrides/config/modularmachinery/recipes/mob_loot_fabricator_passive.json, overrides/config/modularmachinery/recipes/mob_loot_fabricator_slime.json
- add liquid meat output to the passive mobs MLF recipe
- add a new slime type to the MLF, giving the 3 tinkers slimeballs, vanilla slimeballs, aether legacy swet balls, and industrial foregoing pink slime balls
- resolve #930
=> resolve #930

overrides/scripts/Events.zs
Now it drops into the world on death instead of going into the grave. While this may be a slight problem in some specific situations, the only other viable solution is completely removing death lists, which is undesirable (and also causes those same slight problems in some specific situations more frequently).
=> Resolve Tomb Many Graves Death Lists Causing NBT Corruption

overrides/config/undergroundbiomes/ores/astralsorcery.json, overrides/config/undergroundbiomes/ores/thermalfoundation.json, overrides/scripts/Events.zs, overrides/scripts/OreProcessingAdditions.zs
- Remove Thermal Foundation Platinum, Astral Sorcery Rock Crystal, and Astral Sorcery Starmetal from the list of UB ores.
- Make UB ores drop the ore they are based on when Silk Touched instead of their actual raw ore.
=> improve UB ores behavior on being silk touched

overrides/config/jei/itemBlacklist.cfg, overrides/scripts/ThermalDynamics.zs
Move Viaducts into early Mekanism, costing Elite Circuits, increase quantity gained, and add a quest describing them.
=> move Viaducts into early Mekanism

overrides/config/UniversalTweaks.cfg
This disables two Universal Tweaks features:
- The Storage Drawers "Item Handlers" tweak, as it causes issues with Drawer Controller insertion.
- The Item Entities tweak, as the combination of itemstacks breaks some setups - most notably Botania. Resolves #941.
=> resolve #941 and a storage drawer controller bug

overrides/config/natura.cfg
it was always just this simple. now, no more random natura stuff in dimensions where it shouldnt spawn (eg dreadlands)
=> stop natura generating stuff in wrong dimensions

overrides/scripts/HandFramingTool.zs
before this, if you had a HFT in your offhand and used it on the side of a drawer/on drawer trim, you would crash
now, it works!
=> stop crash when using HFT in offhand

overrides/config/jei/itemBlacklist.cfg, overrides/scripts/ActivateBlockJEI.zs, overrides/scripts/Totemic.zs
resolve #899
- Hid all but Stripped Red Cedar Logs & variants from JEI, as the others were unobtainable.
- Add an Activate Block Interaction to JEI for the Bark Stripper converted Red Cedar Logs into Stripped Red Cedar Logs.
- Add crafting recipes for Stripped Red Cedar Pillars and Stripped Red Cedar Pillar Bases.
=> Totemic Stripped Logs Fixes

overrides/config/jei/itemBlacklist.cfg, overrides/scripts/ProjectRedCore.zs
The projectred electrotine still shows in the EMC tablet, but at least it’s removed from JEI
=> Fix ProjectRed electrotine showing in JEI

overrides/config/astralsorcery.cfg, overrides/config/modularmachinery/recipes/mob_loot_fabricator_box.json, overrides/scripts/BloodMagic.zs, overrides/scripts/ContentTweakerRecipes.zs, overrides/scripts/DivineRPG.zs, overrides/scripts/Events.zs, overrides/scripts/Excavator.zs, overrides/scripts/MinecraftRecipes.zs, overrides/scripts/MysticalAgriculture.zs, overrides/scripts/Roots.zs
resolves #977
has a number of smaller changes
- Add conversion recipes for each soul gem tier (instead of just the final tier) that also copy will quantity instead of resetting.
- Adjust Angelic Chestplate recipe to cost Elevatium instead of an Angel Ring.
- Add a Mystical Agriculture recipe for Ender Air.
- Make the Mystical Agriculture recipe for Dragon's Breath use Ender Air.
- Add a Mob Loot Fabricator recipe for Extended Crafting Ender Nuggets.
- Add a quest describing Botania Lenses and how mana transfer works.
- Prevent the Matter Transporter picking up a Black Hole Tank/Unit.
- Remove a duplicate tooltip for Imp Leather.
- Add a few more animals - Imps, Buffalo, Eagles, and Wisps - to Root's Animal Harvest Ritual.
- Allow use of any Mossy Cobblestone in the Roots Grove …
=> Maintain May 2023

overrides/scripts/JEI/Excavator.zs
i messed up with git and blew up #1009. this is a cherry-picked commit of the actually desired change, because this was way easier than actually fixing what i broke.
https://github.com/Divine-Journey-2/Divine-Journey-2/commit/5781853f9a99ffeebf790be06c2eb524438dfd01
=> Fixed typo in excavator vein registration

overrides/scripts/ModSpecific/ContentTweakerRecipes.zs
Resolves #1049 by adding a recipe to make 9 Shattered Mystical Iron Crystals from 1 Mystical Iron Block when dropped as entity
=> Adds recipe to make 9 Shattered Mystical Iron Crystals from 1 Mystical Iron Block when dropped as entity

.github/workflows/release.yml, buildtools/build.py, buildtools/update_version.py, changelog/LATEST.md, manifest.json, overrides/config/CustomMainMenu/mainmenu.json, overrides/config/mputils/addons/mpbasic/mpbasic.cfg
- fixes server changelog not being added to CurseForge.
- replaces files with the specific pack version with `@PACK_VERSION@`.
- add `name` and `version` args to `build.py`.
- shorten `update-version.py`.
- updates some of the libraries used for building.
- fixes `Could not find a changelog` always being appending to the changelog.
=> improve build process

overrides/config/modularmachinery/recipes/laser_focus_actuallyadditions_empowered_diamatine.json, overrides/config/modularmachinery/recipes/laser_focus_actuallyadditions_empowered_emeradic.json, overrides/config/modularmachinery/recipes/laser_focus_actuallyadditions_empowered_enori.json, overrides/config/modularmachinery/recipes/laser_focus_actuallyadditions_empowered_palis.json, overrides/config/modularmachinery/recipes/laser_focus_actuallyadditions_empowered_restonia.json, overrides/config/modularmachinery/recipes/laser_focus_actuallyadditions_empowered_void.json, overrides/config/modularmachinery/recipes/laser_focus_contenttweaker_empowered_crystal_bundle.json, overrides/config/modularmachinery/recipes/laser_focus_contenttweaker_empowered_glod.json
- fixes an issue from #1172 where the laser focus recipes had the incorrect names - this has no impact in-game, its just for consistency.
=> Fix Laser Focus Names

.github/workflows/release.yml
- Fixes the server-changelog step breaking due to the file not being read correctly and thus failing the build process.
=> Fix Buildscript breaking while reading server update

buildtools/build.py, buildtools/update_version.py, changelog/LATEST.md
- fix the issue where `@PACK_VERSION@` appears on the title screen due to not being replaced when the pack is getting released.
- fix the issue where updating would not upload the changelog to curseforge, but instead just the file name.
- clean some methods up in the buildscript.
=> Python update/build script fixes

changelog/LATEST.md, overrides/config/Universal Tweaks - Mod Integration.cfg
- disable the UT config for AA item laser particles, as it tries to load a client-only class on the server
resolve #1239
=> Fix UT causing a server crash

.github/ISSUE_TEMPLATE/000-crash-report.yml, .github/ISSUE_TEMPLATE/001-bug-report.yml, .github/ISSUE_TEMPLATE/002-typo-report.yml, .github/ISSUE_TEMPLATE/003-balance-request.yml, .github/ISSUE_TEMPLATE/004-feature-request.yml, .github/ISSUE_TEMPLATE/005-mod-request.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, changelog/LATEST.md
- recently, issues added a new "type" parameter. ive been adding it manually so far (and went through and applied it to our open issues), this adds it automatically.
- update the templates to fix capitalization and typo issues, update the discord id, etc.
- rename templates so they are ordered in a sensible way to their actual contents instead of alphabetically.
- add `.zip` to the list of outputs of the nightly action.
- an everflowing spring of optimism that perhaps this time github yamls will work correctly the first time
=> Update Github Templates
