Divine-Journey-2/Divine-Journey-2

overrides/scripts/Events.zs

override the normal item use method
resolves #283

Fix DivineRPG spawn items from removing the wrong item

---

manifest.json

resolves #763
- update DJ2 Addons 1.2.1.1 -> 1.2.1.1.1

update DJ2 Addons

---

.github/ISSUE_TEMPLATE/balance-request.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/crash-report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/mod_request.yml
.github/ISSUE_TEMPLATE/typo.yml

its entirely optional, but it should still help.

update issue templates to request discord username

---

overrides/scripts/OpenBlocks.zs

reduce crafting output of openblocks tanks

---

overrides/scripts/LightningCraft.zs

fix ie crafting twice as many copper rods as it should

---

overrides/scripts/Enchantments.zs

fix arcane enscrollator giving books with enchants rather than enchanted books

---

overrides/scripts/ActuallyAdditions.zs

Make ESDs require Wood Casing instead of Iron Casing

---

overrides/scripts/TinkersConstruct.zs

Add melting and casting recipes for the ender block

---

overrides/config/modularmachinery/recipes/auto_infusion_matrix_thaumcraft_fortress_helm_goggles_of_revealing.json
overrides/config/modularmachinery/recipes/auto_infusion_matrix_thaumcraft_fortress_helm_grinning_devil.json

Fix AIM for Thaumium Fortress Helm Variants

---

overrides/scripts/ModularMachinery.zs

the Tender Ender Blender was removed in #722

remove the TEB Blueprint recipe (TEB no longer exists)

---

overrides/scripts/Events.zs

you know, this really makes me appreciate the ability to reload because the number of times i had to reload to test this (89 times, from the log and my well renowned counting ability) is nearly 6 hours (4 minute load time). 
resolves #261

Fix IE Workbench sometimes voiding drops 

---

overrides/config/modularmachinery/recipes/auto_infusion_matrix_thaumicenergistics_blank_knowledge_core.json

Fix Knowledge Core Recipe in AIM

---

overrides/config/tips.cfg

Should improve on what #825 is doing

Fixes a few more links

---

overrides/scripts/ActuallyAdditions.zs
overrides/scripts/AstralSorcery.zs

Stair Equality

---

overrides/scripts/Events.zs

Fixes Permission Issues with Sponge Servers.

Use ContentTweaker instead of Zenutils for Commands

---

overrides/scripts/RFTools.zs

Remove duplication with button screen modules

---

overrides/scripts/AetherLegacy.zs

Holystone Recipe

---

manifest.json
modlist.html
overrides/config/neenergistics/neenergistics.cfg

resolve #792, hopefully address #851

update ae2 and add NEE

---

overrides/scripts/QuantumFlux.zs

For all those who don't know this is dropped from Endermen.

Add tooltip to Ender Crystal

---

overrides/config/UniversalTweaks.cfg
overrides/config/jei/itemBlacklist.cfg
overrides/config/modularmachinery/machinery/chemical_caster.json
overrides/scripts/AppliedEnergistics2.zs

quick fixes for 2.19.1

---

overrides/config/enderio/recipes/user/user_recipes.xml
overrides/scripts/RFTools.zs

- fix crash involving enderio's xml due to #934
- fix error involving RFTools addHiddenShapeless due to #901

fix a few small things quickly

---

overrides/config/natura.cfg

Fixes #975 
May be a better fix, but this works.

Thornvine fix

---

overrides/scripts/AetherLegacy.zs

Add Golden Berry Recipe

---

overrides/scripts/UnifyingIngotsAndBlocks.zs

Fixes a few ingots being available through EMC and nowhere else

It's not all Alchemistry's fault

---

overrides/config/jei/itemBlacklist.cfg
overrides/config/undergroundbiomes/ores/thermalfoundation.json
overrides/scripts/Chisel.zs
overrides/scripts/OreProcessingAdditions.zs

Also fixes two typos in the comments lol
I also remembered that you can change through the ore types in the Ore Dictionarificator, so maybe this is not needed then... Welp... ¯\_(ツ)_/¯

Add Chisel for UB, erebus, atum, lightningcraft, GC ore variants

---

overrides/scripts/Bewitchment.zs

bewitchment candles no longer have the same recipe as quark candles

fix duplicate candle recipe

---

manifest.json
modlist.html
overrides/config/CustomMainMenu/mainmenu.json
overrides/config/mputils/addons/mpbasic/mpbasic.cfg
overrides/config/mputils/changelog.txt

Merge in 2.19.4

---

overrides/scripts/ModSpecific/ExtraUtilities2.zs

it can be crafted in any 3x3 crafting grid. still explodes after 10s or if you leave it, though.

remove false unstable ingot tooltip

---

buildtools/build.py

- apply to server files and confirm exists
- fixes the crash added in #1144

fix build process

---

buildtools/update_version.py

fix the wrong line in `update_version.py` being changed incorrectly in #1189

Update Python update_version script
